"""atotaltime

Revision ID: 34d4e40fdaf9
Revises: 71519982d96d
Create Date: 2020-11-06 16:05:23.401346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d4e40fdaf9'
down_revision = '71519982d96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('atotal_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'atotal_time')
    # ### end Alembic commands ###
