"""datatimechange.

Revision ID: 447862bfcfae
Revises: 88194cd3601b
Create Date: 2020-11-03 13:36:48.173843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447862bfcfae'
down_revision = '88194cd3601b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('aprice', sa.Float(), nullable=True))
    op.add_column('auto', sa.Column('end_of_rent', sa.DateTime(), nullable=True))
    op.add_column('auto', sa.Column('rented', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'rented')
    op.drop_column('auto', 'end_of_rent')
    op.drop_column('auto', 'aprice')
    # ### end Alembic commands ###
