"""newclass.

Revision ID: 71519982d96d
Revises: ccb31af08c1f
Create Date: 2020-11-06 11:51:36.714838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71519982d96d'
down_revision = 'ccb31af08c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_id', sa.Integer(), nullable=True),
    sa.Column('rented', sa.DateTime(), nullable=True),
    sa.Column('end_of_rent', sa.DateTime(), nullable=True),
    sa.Column('rentprice', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('auto', sa.Column('rent_count', sa.Integer(), nullable=True))
    op.add_column('auto', sa.Column('total_price', sa.Float(), nullable=True))
    op.add_column('auto', sa.Column('total_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'total_time')
    op.drop_column('auto', 'total_price')
    op.drop_column('auto', 'rent_count')
    op.drop_table('rentlog')
    # ### end Alembic commands ###
