"""astatusBool.

Revision ID: 88194cd3601b
Revises: ac13435d0ac2
Create Date: 2020-11-03 12:06:20.010805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88194cd3601b'
down_revision = 'ac13435d0ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('astatus', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'astatus')
    # ### end Alembic commands ###
