"""datatimechange2.

Revision ID: 8d8f5df58df8
Revises: 447862bfcfae
Create Date: 2020-11-03 13:53:40.989491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8f5df58df8'
down_revision = '447862bfcfae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('aend_of_rent', sa.DateTime(), nullable=True))
    op.add_column('auto', sa.Column('arented', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'arented')
    op.drop_column('auto', 'aend_of_rent')
    # ### end Alembic commands ###
