"""Initial.

Revision ID: ac1b27e7ff7e
Revises: f9512be05fa5
Create Date: 2020-10-26 19:16:02.302715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1b27e7ff7e'
down_revision = 'f9512be05fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('transmission', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'transmission')
    # ### end Alembic commands ###
