"""nullable.

Revision ID: b5021f984612
Revises: 34d4e40fdaf9
Create Date: 2020-11-09 15:54:50.396755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5021f984612'
down_revision = '34d4e40fdaf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('date_end', sa.DateTime(), nullable=True))
    op.add_column('rentlog', sa.Column('date_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rentlog', 'date_end')
    op.drop_column('auto', 'date_end')
    # ### end Alembic commands ###
