"""imgs.

Revision ID: b8d69fcf1937
Revises: b5021f984612
Create Date: 2020-11-09 21:14:57.778040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d69fcf1937'
down_revision = 'b5021f984612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('img_url2', sa.String(length=128), nullable=True))
    op.add_column('auto', sa.Column('img_url3', sa.String(length=128), nullable=True))
    op.add_column('auto', sa.Column('img_url4', sa.String(length=128), nullable=True))
    op.add_column('auto', sa.Column('img_url_2', sa.String(length=128), nullable=True))
    op.add_column('auto', sa.Column('img_url_3', sa.String(length=128), nullable=True))
    op.add_column('auto', sa.Column('img_url_4', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'img_url_4')
    op.drop_column('auto', 'img_url_3')
    op.drop_column('auto', 'img_url_2')
    op.drop_column('auto', 'img_url4')
    op.drop_column('auto', 'img_url3')
    op.drop_column('auto', 'img_url2')
    # ### end Alembic commands ###
