"""priceagain

Revision ID: ccb31af08c1f
Revises: 8a3f94602c76
Create Date: 2020-11-05 16:48:47.180150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb31af08c1f'
down_revision = '8a3f94602c76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('auprice', sa.Float(asdecimal=True), nullable=True))
    op.add_column('auto', sa.Column('autprice', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto', 'autprice')
    op.drop_column('auto', 'auprice')
    # ### end Alembic commands ###
