"""Initial migration.

Revision ID: f9512be05fa5
Revises: 
Create Date: 2020-10-26 14:47:37.665209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9512be05fa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('description', sa.String(length=128), nullable=True))
    op.drop_column('auto', 'img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto', sa.Column('img_url', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('auto', 'description')
    # ### end Alembic commands ###
